modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="simpleradio"
version="1.0.0"
displayName="Simple Voice Radio"
authors="CodinGlitch"
description='''Simple voice radio mod ported to NeoForge 1.21.1'''

[[dependencies.simpleradio]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpleradio]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.22]"
ordering="NONE"
side="BOTH"

[[dependencies.simpleradio]]
modId="voicechat"
type="required"
versionRange="[0,)" # This covers all 2.x versions, including 2.6.14
ordering="NONE"
side="BOTH"