modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="simpleradio"
version="1.0.0"
displayName="Simple Radio"
authors="CodinGlitch"
description="A simple radio mod for Minecraft."

[[dependencies.simpleradio]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpleradio]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"